trigger:
  branches:
    include:
      - develop

pool:
  name: 'Default'

steps:
- script: |
    python3 -m venv .venv
    source .venv/bin/activate
    python -m pip install --upgrade pip setuptools wheel
    pip install -r requirements.txt
  displayName: 'Install dependencies in virtualenv'

- script: |
    source .venv/bin/activate
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'Run pytest in virtualenv'