trigger:
  branches:
    include:
      - develop

pool:
  name: 'Default'

steps:
- script: |
    python3 --version
    python3 -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'